examples/query.example.graphql
=> Prettifies query.example

.circleci/config.yml
=> ci: fix indentation in circle config

.gitignore, lib/dataSourceParser.js, lib/resolverMaker.js, lib/schemaParser.js, server.js
JIRA: https://issues.jboss.org/browse/AEROGEAR-3435
Divide code into modules
=> Initial code division

package-lock.json, package.json, server/lib/dataSourceParser.js, server/lib/dataSourceParser.test.js, server/lib/resolverMaker.js, server/lib/resolverMaker.test.js
JIRA: https://issues.jboss.org/browse/AEROGEAR-3435
- Introduced Ava testing framework
- Added unit tests to where it makes sense.
- While writing tests for base cases, I noticed there are some base cases not handled. I added handling for them.
- Validate Handlebars templates in advance to fail early (was waiting until a query/mutation is executed to fail)
- No integration tests!
Verification:
1. Do run npm test
2. Do start the app, execute some stuff over Graphiql
=> AEROGEAR-3435: Add initial unit tests and handle some unhandled base cases

server/lib/datasources/dataSourceParser.js, server/lib/datasources/dataSourceParser.test.js, server/lib/datasources/parsers/nedb.js, server/lib/datasources/parsers/postgres.js, server/lib/resolvers/builders/nedb.js, server/lib/resolvers/builders/postgres.js, server/lib/resolvers/resolverMapper.js
JIRA: https://issues.jboss.org/browse/AEROGEAR-7637
How to verify:
- docker-compose -p aerogeardatasyncserver up
- npm run db:init:memeo:postgres
- npm run dev:memeo
- Go to http://localhost:8000/graphiql and execute `allMemes`. Should be all good
- `docker stop aerogeardatasyncserver_postgres_memeo_1`
- Execute `allMemes` again, should see error message
- `docker start aerogeardatasyncserver_postgres_memeo_1`
- Execute `allMemes` again, should be all good
Also, do the same for config database (Docker image with name `aerogeardatasyncserver_postgres_1`).
This time, you should see log messages in data-sync server like `retrying pubsub connection`. When you start the config database again, you should see a log message like `connected to pubsub.`
=> Postgres reconnect

server/lib/resolvers/builders/nedb.js, server/lib/resolvers/builders/postgres.js, server/lib/util/logger.js, server/server.js
JIRA: https://issues.jboss.org/browse/AEROGEAR-7645
Added audit logging to resolvers.
How to verify:
* Run these:
```
docker-compose-up
npm run db:init:memeo:inmem
OR
npm run db:init:memeo:postgres
npm run dev
```
* Go to localhost:8000/graphiql
* Execute `createMeme`. You should see this log entry:
```
{
"level": 30,
"time": 1533023633355,
"pid": 7441,
"hostname": "localhost.localdomain",
"tag": "AUDIT",
"msg": "",
"requestId": 3,
"operationType": "mutation",
"parentTypeName": "Mutation",
"path": "createMeme",
"success": true,
"arguments": {
"photoUrl": "https://test.com"
},
"v": 1
}
```
* Execute `allMemes` and you should see another log entry
* Adjust the files in https://gist.github.com/aliok/6bac95a008b146e678041822fba438a5
* Run `docker-compose up`
* Run `npm run …
=> AEROGEAR-7645 audit logs

package-lock.json, package.json, server/lib/resolvers/builders/nedb.js, server/lib/resolvers/builders/postgres.js, server/lib/resolvers/resolverMapper.js, server/lib/util/logger.js, server/metrics/index.js, server/server.js
https://issues.jboss.org/browse/AEROGEAR-7650
`npm install` (new dependency **prom-client** has been added)
`docker-compose -p aerogeardatasyncserver up`
`npm run db:init:memeo:postgres`
`npm run dev`
1. Go to http://localhost:8000/metrics and check that metrics data is available
1. Go to http://localhost:8000/graphiql, paste in following and run it:
```
mutation createprofile {
createProfile(email: "jon@doh.com", displayname: "Jon D Oh", pictureurl: "https://cdn1.thr.com/sites/default/files/imagecache/scale_crop_768_433/2011/10/doh_a.jpg") {
email
id
displayname
}
}
query getAllMemes {
allMemes {
id
likes
comments {
id
owner
comment
}
}
}
```
3. Refresh http://localhost:8000/metrics and check that you see a record like 
```
resolver_timing_ms{datasource_type="Postgres",operation_type="mut …
```
=> Metrics endpoint + resolver metrics

examples/memeolist.query.examples.graphql, examples/memeolist.query.graphql, examples/memeolist.variables.json, package.json, sequelize/seeders/memeolist-example-postgres.js, server/config/index.js
Provide examples in the form that can be used in Android and IOS client.
Still left examples for js client.
=> Add subscription example

.github/CODE_OF_CONDUCT, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Add the standard files for github
It will be helpful for contributors be able to follow the guidelines
- Adding files with templates to open PR's and Issues as the guidelines
=> task: Add standard github files

package-lock.json, package.json, server/lib/resolvers/resolverMapper.js, server/lib/resolvers/wrapResolverWithHooks.js, server/lib/resolvers/wrapResolverWithHooks.test.js
Related issues:
* [AEROGEAR-7658](https://issues.jboss.org/browse/AEROGEAR-7658)
=> Add pre and post hook

sequelize/seeders/memeolist-example-postgres.js, server/config/index.js
* makes the graphiql subscriptions endpoint configurable by env variable (will be done by the data-sync-apb)
* fixes bad naming on example postgres datasource
=> fix: minor fixes

server/metrics/index.js
https://issues.jboss.org/browse/AEROGEAR-7650
* fixed logging response errors to metrics
* replaced gauges with histograms
* added resetting metrics after each `/metrics` request
* added request_resolved_total metric
=> Histograms + metric resetting

package-lock.json
Suggested to push the changes
Update package-lock.json file after npm install
Run it? The service ran successfully following the steps in the README
=> updating NPM package-lock

README.md, integration_test/util/testApolloClient.js, package-lock.json, package.json, server/config/index.js, server/lib/schemaParser.js, server/server.js
https://issues.jboss.org/browse/AEROGEAR-7787
Updated the Apollo version
Changed the config so that playground could use the old graphiql config
=> updated apollo version, added config for playground instead of graphiql

keycloak/realm-export.json
Add realm user and realm role to sample keycloak file. 
Updates were made also on security server.
=> Add voter user and role to sample memeo realm

README.md, package.json
Fixes the issues with docker-compose commands not working right
=> fix: standardise docker-compose commands

keycloak/realm-export.json, server/security/index.js, server/server.js
Allow to use playground with keycloak
1. localhost:8000/login
2. Login to keycloak
3. Copy token
4. Use token in the playground
http://www.giphy.com/gifs/ukgZfagWxYxkhqIQh2
Refresh playground tab with token after login (it's attached to req.session)
=> Add login middleware

sequelize/seeders/memeolist-example-shared.js
=> Add admin role

README.md
Added a small readme section for using Keycloak for local development
https://issues.jboss.org/browse/AEROGEAR-7839
=> added local development flow for keycloak

.dockerignore
Changes are pretty self-explanatory.
=> fix: .dockerignore updates

server/server.js
Code is being duplicated in `server.js`.
Improve a litle bit the code, so it doesn't have the practically same `newExpressApp()` and `newApolloServer()` two times in there.
Improve readability.
Create `newServer()` function that covers new server and app creation and is called from proper places.
=> Removed code duplication in `server.js`

server/security/services/keycloak/schemaDirectives/hasRole.js, server/security/services/keycloak/schemaDirectives/hasRole.test.js
Adds some extra logging just to make things clearer
=> fix: add extra logging to hasRole

server/server.js
ensure the directives are actually loaded...
=> fix: ensure directives are added

.circleci/config.yml
Pass the right tag to release validator
=> Fix release pipeline

package.json
=> release-tag

sequelize/seeders/memeolist-example-shared.js
Fixes error 
```
Invalid hasRole directive on field <blahblah> on parent Mutation`
...
"type" is not allowed
```
=> fix: memeolist hasRole directive

README.md, keycloak/docker-compose.yml, package.json
Currently having Keycloak on 8080 was causing some problems with the UI (as this is the port it uses). Means we can't test everything at once.
=> swapped keycloak port to 9090

README.md, package-lock.json
Tracking the work of Data Sync I decided to install it and run through the README. I noticed some typos and unclear instructions
Grammatical and typo fixes and easier navigation links
Better user experience particularly when later sections refer to earlier
N/A, local docs change
N/A just a README change, verify my grammar and structure!
PS.: Add images and/or .gifs to illustrate what was changed if this pull request modify the appearance/output of something presented to the users.
=> Updated README for clarity and typos

README.md
There is no relevant ticket. Just making some minor fixes and refactoring of the Readme.
=> doc: minor fixes to readme
