.circleci/config.yml
Adds a CircleCI config that will allow docker release stuff.
The actual docker commands should be implemented in a separate PR
@david-martin I have two suggestions for the docker build commands.
Either implement them directly in `package.json` or create a `scripts` directory with the appropriate bash scripts that perform the right commands, then wire up the commands in `package.json` to the scripts
=> feat: initial CircleCI config

README.md, nodemon.json, package.json
This PR makes some very small, developer friendly changes,
* reorders some bits in package.json
* changes some of the npm commands
* puts a placeholder test command
* removes the nodemon.json config that tries to auto lint. This regularly causes crashes which is pretty bad from a developer experience perspective
* adds a precommit hook which runs tests - we can keep this pretty lightweight by running integration tests in a different command. (If we need)
Ping @aliok @david-martin
=> fix: tidy up package.json, add pre-commit hook for tests

README.md, examples/resolver-mappings.example.json, server/lib/dataSourceParser.js, server/lib/dataSourceParser.test.js, server/lib/resolverMaker.js, server/lib/resolverMaker.test.js, server/lib/schemaParser.js
This PR doesn't introduce any new features or functionality. Just does some refactor before I move onto splitting resolvers and data sources into their own file.
Data Source Definitions used to look like this:
```json
{
"Query": {
"readNote": {
"dataSource": "p1",
"requestMapping": "SELECT id, title, content, timestamp FROM \"Notes\" WHERE id='{{context.arguments.id}}';",
"responseMapping": "{{toJSON context.result.[0]}}"
}
},
"Mutation": {
"createNote": {
"dataSource": "p1",
"requestMapping": "INSERT INTO \"Notes\" (\"id\",\"title\",\"content\",\"timestamp\") VALUES ('{{context.arguments.id}}','{{context.arguments.title}}','{{context.arguments.content}}',{{context.arguments.timestamp}}) RETURNING *;",
"responseMapping": "{{toJSON context.result.[0]}}"
}
}
}
```
now they look like this: …
=> refactor: simplify dataSourceParser and resolverMaker

server/lib/datasources/dataSourceParser.js, server/lib/datasources/parsers/nedb.js, server/lib/datasources/parsers/postgres.js, server/lib/resolvers/resolverMapper.js, server/lib/schemaListeners/schemaListenerCreator.js, server/lib/schemaParser.js, server/server.js
https://issues.jboss.org/browse/AEROGEAR-3646
Verify:
1. Start the app like `node index.js` (no Docker or Kube)
2. Note the PID for the process (`ps -ax | grep data-sync`)
3. Send SIGTERM: `kill -SIGTERM 1234`
I tested the same thing within Docker. 
1. Build and run the container
2. `docker stop <container>`
You will see logs.
I didn't really test stuff on Kube. It will work on Kube since it works on Docker.
Commits:
* https://github.com/aerogear/data-sync-server/pull/17/commits/31f7cddc01b2a411991013d0745ef23838ec986c: Implemented initial handler for shutdown on SIGTERM
* https://github.com/aerogear/data-sync-server/pull/17/commits/ad4bb09b76dab4e1ded73a59da68ed1cb1aa3920: Handling more signals
* https://github.com/aerogear/data-sync-server/pull/17/commits/ee0590f8d0a168b675afaa6376692fbf …
=> Graceful shutdown

sequelize/models/graphQLSchema.js, sequelize/seeders/20180704100455-notes-example.js
This column will be used for the following:
* Human friendly display name in the UI
* default filename used during schema download
=> feat: add name column to schema

.dockerignore, README.md, examples/memeolist.query.graphql, package.json, sequelize/models/resolver.js, sequelize/seeders/20180704100455-notes-example.js, sequelize/seeders/20180711143600-memeolist-example.js, server/config/index.js, server/lib/resolvers/builders/nedb.js
@darahayes 
This PR adds 2 additional npm commands.
* db:init:memeo - Creates the DB with memeo list schema and resolvers
* dev:memeo - Feeds the memeolist example queries to Graphiql so that when you go to localhost:8000/graphiql, you can see those queries.
The schema itself is not complete. I am working on it at the moment.
=> Devl workflow for memeolist

.dockerignore, package-lock.json, package.json
This PR makes some changes such that it's possible to run `npm run db:init:memeo' inside the running container image.
This allows us to do a little hack where we can use the OpenShift UI to get a shell inside the running container and then we can manually execute `npm run db:init:memeo`. This will enable us to do the demo.
=> hack: allow db:init:memeo run inside container

server/lib/resolvers/compiler.js
I found an issue where the handlebars templates (request and response mappings) would escape unicode characters. For example, in the memeolist app this led to the `photoUrl` property being broken and it meant that in the app, the image could not be displayed
ping @aliok @wtrocki
=> fix: ensure handlebars does not escape unicode characters

.eslintrc, package-lock.json, package.json, scripts/sync_models.js
Review the code to make sure console.log/.info/.error/etc. is not used. Configure linter to complain about "console" usage
StandardJS is just a wrapper around ESLint with custom ruleset. It makes sense in 99% cases but we want to disable the usage of `console`. I had to use sharable configs feature of ESLint and extend StandardJS rules by `no-console` rule.
How to verify:
add `console.log('foo')` to somewhere and run `npm run lint`. You should see failure.
Make sure the formatter still works. 
* Change a single quoted string to double quoted string
* Run `npm run format`
* The string should be quoted with single quites
=> AEROGEAR-7646

index.js, integration_test/subscriptions.hot.reload.integration.test.js, sequelize/seeders/memeolist-example-shared.js, server/server.js
This PR ensures that the subscription server is closed and that a new one is instantiated when a schema change occurs.
It also adds an integration test to test this case.
It also makes a few minor changes in startup sequence:
* add the unhandledRejection and unhandledException listeners at the very beginning. Because these were being added **after** initialisation + startup, any errors happening in that time would be swallowed
* Same thing again for the stop signals listeners
=> fix: Subscriptions Hot Reload

.circleci/config.yml, .eslintignore, .gitignore, README.md, package-lock.json, package.json
This PR adds an additional step to the CI config which runs both integration and unit tests and outputs code coverage to Coveralls.io
You can see the project in coveralls here: https://coveralls.io/github/aerogear/data-sync-server
=> feat: add code coverage reporting

server/lib/resolvers/resolverMapper.js, server/lib/resolvers/wrapResolverWithHooks.js, server/lib/resolvers/wrapResolverWithHooks.test.js
https://issues.jboss.org/browse/AEROGEAR-7764
Adds additional context to the pre and post hook payloads
This really isn't necessary, however if you would like to verify you can run a test hook server as follows:
```
docker run -p 3000:3000 darahayes/echo-server | npx pino-pretty
```
Then go edit the `createMeme` resolver inside `sequelize/seeders/memeolist-example-postgres.js` to have these extra fields:
```
preHook: 'http://localhost:3000',
postHook: 'http://localhost:3000'
```
Then run the sync server as follows
```
npm run db:init:memeo:postgres && npm run dev:memeo
```
Now use the GraphiQL interface to create a profile, then create a meme.
Go back to the logs for the `echo-server` and you should see some logs similar to the following:
```
[1534323262218] INFO (73692 on …
```
=> fix: add extra context to pre and post hook payload

server/lib/schemaDirectives/hasRole.js, server/lib/schemaParser.js
This PR provides a skeleton implementation for a `hasRole` directive which can be applied to a schema.
https://www.apollographql.com/docs/graphql-tools/schema-directives.html#Enforcing-access-permissions
This skeleton implementation is where we can now figure out how to do the integration with keycloak.
=> feat: initial empty hasRole implementation

.gitignore, README.md, package-lock.json, package.json
https://issues.jboss.org/browse/AEROGEAR-7810
Publishing code coverage results with **coveralls** was recently a bit flaky (was randomly failing) - we've decided to go with **codecov** to see if it improves stability.
* test coverage setup is done by following the steps in https://github.com/istanbuljs/nyc#integrating-with-codecov
* codecov token is stored in environment variable in circleci project
Assuming that if user would start developing by cloning this repo first, the name of the folder he/she would work in would be named 'data-sync-server'. By following the steps in readme,  running `docker-compose up` would create container names prefixed with the folder name.
For this reason, it makes sense to change the prefix in scripts to 'data-sync-server'.
Wdyt?
=> Replaced coveralls with codecov

package.json, server/server.js
https://issues.jboss.org/browse/AEROGEAR-7815
Fix the bug where the healthz endpoint was returning a 404 after a schema reload
Causing health checks on Openshift to fail
Move the code into the newExpressApp function as suggested in the jira
- run the server & seed db
- run the ui
- hit the server url + /healthz in the browser - should get message : 
`{"ok":true,"checks":[{"Database Connectivity":true}]}`
- make a change in the ui such as add a data source which will trigger a schema reload
- verify the endpoint is still giving a healthy response as above and not a 404
@darahayes I think I have implemented this as you suggested - I was able to replicate the issue locally using the method I described
=> AG-7815 refactor newExpressApp function 

integration_test/datasyncservice.smoke.test.js
This small integration test is a smoke test that ensures that the actual `DataSyncService` class can be initialised and started. All of the other tests don't actually verify this because we use a special `RestartableSyncService` class for the rest of the tests.
This is important because this is the actual class that is used in a real scenario and also this should bump our code coverage.
=> fix: add smoke test for server startup

server/security/services/keycloak/AuthContextProvider.test.js, server/security/services/keycloak/schemaDirectives/hasRole.js, server/security/services/keycloak/schemaDirectives/hasRole.test.js
This PR adds some basic unit tests to cover the tricky logic in the hasRole implementation for keycloak. There should be integration tests for the overall functionality, but this should at least guarantee that the logic within that function is solid and protects us from accidentally breaking it.
Related ticket: https://issues.jboss.org/browse/AEROGEAR-7841
=> fix: unit tests for keycloak hasRole and AuthContextProvider implementations

.dockerignore
To mount examples into playground (temporarily).
We need that to have this files in the docker image so we can populate example queries.
=> Include examples in dockerimage

server/server.js
Server was dropping security when schema was reloaded.
Some parameters are not passed in `server/server.js` in `newApolloServer()` and `newExpressApp` while schema is being reloaded.
Pass the missing parameters.
1. Start server with Keycloak enabled
2. Call to `/graphql` endpoint invokes Keycloak login
3. Do schema update (using for example `data-sync-ui`)
Expected: Call to `/graphql` endpoint invokes Keycloak login (when not logged in)
=> Bugfix: Server drops security when schema reloaded

package-lock.json, package.json, server/lib/util/internalServerError.js, server/lib/util/internalServerError.test.js, server/security/services/keycloak/schemaDirectives/hasRole.js, server/security/services/keycloak/schemaDirectives/hasRole.test.js, server/server.js
This PR adds the ability to specify an array of roles in the `hasRole` directive for keycloak. The following syntax is now supported:
```
@hasRole(role: ["editor", "admin", "reader"])
@hasRole(role: ["editor", "admin", "reader"], type: "client")
@hasRole(role: ["editor", "admin", "reader"], type: "realm")
@hasRole(role: "admin")
@hasRole(role: "admin", type: "client")
@hasRole(role: "admin", type: "realm")
```
One of the main things I want to draw attention to is that I've introduced a new dependency called Joi. [Joi](https://npm.im/joi) is one of the most sophisticated validation libraries I've ever used.
You can see an example of how it's being used in the `validateArgs` function
```js
const allowedTypes = ['client', 'realm']
// joi is dope. Read the docs and discover the magic.
// …
```
=> feat: support array of roles in keycloak hasRole

examples/memeolist.query.examples.graphql, examples/memeolist.query.graphql, examples/memeolist.tables.sql, sequelize/seeders/memeolist-example-inmem.js, sequelize/seeders/memeolist-example-postgres.js, sequelize/seeders/memeolist-example-shared.js
This PR:
* Remove comments from Meme (type and query)
* Add a new Query (comments by memeid)
* Add Owner relationship from Comment
* Fix Owner relationship on Meme (from Array to a single type)
* Fix responseMapping for all postgres querys
* Probably something else I can't remember right now :bowtie:
=> Update comment schema

.circleci/config.yml, docker-compose.yml, integration_test/auth.integration.test.js, integration_test/auth.integration.test.keycloak.js, integration_test/config/auth.complete.memeo.schema.only.js, integration_test/config/keycloak.json, integration_test/config/realm-export.json, server/config/index.js
https://issues.jboss.org/browse/AEROGEAR-7906
* to have tests dependent only on locally running services - in this case, Keycloak
Use local Keycloak instance for running integration tests
Why not
* add keycloak image to `docker-compose.yml`
* add script for configuring local keycloak instance
* modify circleci.yml file so circleci will use local keycloak instance
* clone this branch
* run `docker-compose -p sync up` and wait for keycloak to spin up
* run `npm run test:integration:auth` (to test only auth) or `npm run test:integration` to run all integration tests
You might ask: Why didn't he assigned the roles to a user when creating them?
[Click to show the answer.](https://stackoverflow.com/questions/49818453/client-roles-havent-assigned-during-creating-new-user-in-keycloak) I spend …
=> feat: local Keycloak instance for integration tests
